/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainSiLogin;

import clase.DBConnection;
import clase.criptare;
import com.mysql.jdbc.Connection;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author TechSolutions
 */
public class Login extends javax.swing.JFrame {
    Connection connect = DBConnection.getDbCon().connect;
    PreparedStatement ps = null;
    static ResultSet rs = null;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jusername = new javax.swing.JTextField();
        jpassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicatie Management - Login");
        setFocusCycleRoot(false);
        setMaximumSize(new java.awt.Dimension(405, 277));
        setMinimumSize(new java.awt.Dimension(405, 277));
        setPreferredSize(new java.awt.Dimension(405, 277));
        setResizable(false);
        getContentPane().setLayout(null);

        jusername.setMaximumSize(new java.awt.Dimension(5, 20));
        jusername.setMinimumSize(new java.awt.Dimension(5, 20));
        getContentPane().add(jusername);
        jusername.setBounds(190, 100, 180, 30);

        jpassword.setMaximumSize(new java.awt.Dimension(5, 20));
        jpassword.setMinimumSize(new java.awt.Dimension(5, 20));
        jpassword.setPreferredSize(new java.awt.Dimension(5, 20));
        jpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jpassword);
        jpassword.setBounds(190, 160, 180, 30);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 200, 100, 23);

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 200, 100, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Lucrare Licenta\\AplicatieSuportPentruManagerulJucatorilor\\Login-2.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 250);

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Sql = "SELECT `f`.`denumire`, `f`.`adauga_jucator`, `f`.`modifica_jucator`,`f`.`adauga_antrenor`, `f`.`modifica_antrenor`, `f`.`adauga_grupa`,`f`.`modifica_grupa`, `f`.`adauga_antrenament`, `f`.`modifica_antrenament`, `f`.`setari`" +
                "  FROM `functie` `f` LEFT JOIN `utilizatori` `u` ON `f`.`id`=`u`.`functie` WHERE `u`.`utilizator`=? AND `u`.`parola`=?;";
        try{
            PreparedStatement ps = connect.prepareStatement(Sql);
            ps.setString(1, jusername.getText());
            if(jpassword.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nu sa completat campul pentru parola!", "Fara Acces", JOptionPane.ERROR_MESSAGE);
            }
            else{
            ps.setString(2, criptare.MD5(jpassword.getText()));
            }
            rs = ps.executeQuery();
            if(rs.next()){
                MainMeniu mm = new MainMeniu();
                mm.setVisible(true);
                setVisible(false);
            }
            else{
                 JOptionPane.showMessageDialog(null, "Utilizator sau parola gresita", "Fara Acces", JOptionPane.ERROR_MESSAGE);
            }    
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login lgin = new Login();
                lgin.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField jusername;
    // End of variables declaration//GEN-END:variables
}
