/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainSiLogin;

import Antrenament.AdaugaAntrenament;
import Grupe.AdaugaGrupa;
import Jucator.AdaugaJucator;
import Utilizatori.AdaugaUsers;
import Jucator.ModificaJucator;
import Utilizatori.ModificaUtilizatori;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author TechSolutions
 */
public class MainMeniu extends javax.swing.JFrame {

    /**
     * Creates new form MainMeniu
     */
    public MainMeniu() throws SQLException {
        initComponents();
        String adauga_jucator = Login.rs.getString("adauga_jucator");
        String modifica_jucator = Login.rs.getString("modifica_jucator");
        privilegii_jucator(adauga_jucator, modifica_jucator);
        
        String adauga_antrenor = Login.rs.getString("adauga_antrenor");
        String modifica_antrenor = Login.rs.getString("modifica_antrenor");
        privilegii_antrenor(adauga_antrenor, modifica_antrenor);
        
        String adauga_grupa = Login.rs.getString("adauga_grupa");
        String modifica_grupa = Login.rs.getString("modifica_grupa");
        privilegii_grupa(adauga_grupa, modifica_grupa);
        
        String adauga_antrenament = Login.rs.getString("adauga_antrenament");
        String modifica_antrenament = Login.rs.getString("modifica_antrenament");
        privilegii_antrenamente(adauga_antrenament, modifica_antrenament);
        
        String setari = Login.rs.getString("setari");
        privilegii_setari(setari);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuJucator = new javax.swing.JMenu();
        jMenuJucatorAdauga = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuJucatorModifica = new javax.swing.JMenuItem();
        jMenuAntrenor = new javax.swing.JMenu();
        jMenuAntrenorAdauga = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuAntrenorModifica = new javax.swing.JMenuItem();
        jMenuGrupa = new javax.swing.JMenu();
        jMenuGrupaAdauga = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuGrupaModifica = new javax.swing.JMenuItem();
        jMenuAntrenament = new javax.swing.JMenu();
        jMenuAntrenamentAdauga = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuAntrenamentModifica = new javax.swing.JMenuItem();
        jMenuSetari = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicatie Management - MainMeniu");
        setMinimumSize(new java.awt.Dimension(700, 500));

        jMenuJucator.setText("Jucator");

        jMenuJucatorAdauga.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuJucatorAdauga.setText("Adauga Jucator");
        jMenuJucatorAdauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuJucatorAdaugaActionPerformed(evt);
            }
        });
        jMenuJucator.add(jMenuJucatorAdauga);
        jMenuJucator.add(jSeparator1);

        jMenuJucatorModifica.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuJucatorModifica.setText("Modifica Jucator");
        jMenuJucatorModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuJucatorModificaActionPerformed(evt);
            }
        });
        jMenuJucator.add(jMenuJucatorModifica);

        jMenuBar1.add(jMenuJucator);

        jMenuAntrenor.setText("Antrenor");

        jMenuAntrenorAdauga.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuAntrenorAdauga.setText("Adauga ");
        jMenuAntrenorAdauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAntrenorAdaugaActionPerformed(evt);
            }
        });
        jMenuAntrenor.add(jMenuAntrenorAdauga);
        jMenuAntrenor.add(jSeparator2);

        jMenuAntrenorModifica.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuAntrenorModifica.setText("Modifica");
        jMenuAntrenorModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAntrenorModificaActionPerformed(evt);
            }
        });
        jMenuAntrenor.add(jMenuAntrenorModifica);

        jMenuBar1.add(jMenuAntrenor);

        jMenuGrupa.setText("Grupa");

        jMenuGrupaAdauga.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, 0));
        jMenuGrupaAdauga.setText("Adauga");
        jMenuGrupaAdauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGrupaAdaugaActionPerformed(evt);
            }
        });
        jMenuGrupa.add(jMenuGrupaAdauga);
        jMenuGrupa.add(jSeparator3);

        jMenuGrupaModifica.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, 0));
        jMenuGrupaModifica.setText("Modifica");
        jMenuGrupa.add(jMenuGrupaModifica);

        jMenuBar1.add(jMenuGrupa);

        jMenuAntrenament.setText("Antrenament");

        jMenuAntrenamentAdauga.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuAntrenamentAdauga.setText("Adauga");
        jMenuAntrenamentAdauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAntrenamentAdaugaActionPerformed(evt);
            }
        });
        jMenuAntrenament.add(jMenuAntrenamentAdauga);
        jMenuAntrenament.add(jSeparator4);

        jMenuAntrenamentModifica.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuAntrenamentModifica.setText("Modifica");
        jMenuAntrenamentModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAntrenamentModificaActionPerformed(evt);
            }
        });
        jMenuAntrenament.add(jMenuAntrenamentModifica);

        jMenuBar1.add(jMenuAntrenament);

        jMenuSetari.setText("Setari");
        jMenuBar1.add(jMenuSetari);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuJucatorAdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuJucatorAdaugaActionPerformed
        // TODO add your handling code here:
        AdaugaJucator aj = new AdaugaJucator();
        aj.setVisible(true);
    }//GEN-LAST:event_jMenuJucatorAdaugaActionPerformed

    private void jMenuJucatorModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuJucatorModificaActionPerformed
        // TODO add your handling code here:
        ModificaJucator mj = new ModificaJucator();
        mj.setVisible(true);
    }//GEN-LAST:event_jMenuJucatorModificaActionPerformed

    private void jMenuAntrenorModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAntrenorModificaActionPerformed
        // TODO add your handling code here:
        ModificaUtilizatori mu;
        try {
            mu = new ModificaUtilizatori();
            mu.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MainMeniu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuAntrenorModificaActionPerformed

    private void jMenuAntrenamentModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAntrenamentModificaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAntrenamentModificaActionPerformed

    private void jMenuAntrenorAdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAntrenorAdaugaActionPerformed
        // TODO add your handling code here:
        AdaugaUsers au = new AdaugaUsers();
        au.setVisible(true);
    }//GEN-LAST:event_jMenuAntrenorAdaugaActionPerformed

    private void jMenuGrupaAdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGrupaAdaugaActionPerformed
        // TODO add your handling code here:
        AdaugaGrupa ag = new AdaugaGrupa();
        ag.setVisible(true);
    }//GEN-LAST:event_jMenuGrupaAdaugaActionPerformed

    private void jMenuAntrenamentAdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAntrenamentAdaugaActionPerformed
        // TODO add your handling code here:
        AdaugaAntrenament aa = new AdaugaAntrenament();
        aa.setVisible(true);
    }//GEN-LAST:event_jMenuAntrenamentAdaugaActionPerformed

    private void privilegii_jucator(String adauga_jucator, String modifica_jucator){
        if(adauga_jucator.contentEquals("0")){
            jMenuJucator.setVisible(true);
            jMenuJucatorAdauga.setVisible(true);
        }
        else{
            jMenuJucator.setVisible(false);
            jMenuJucatorAdauga.setVisible(false);
        }
        
        if(modifica_jucator.contentEquals("0")){
            jMenuJucator.setVisible(true);
            jMenuJucatorModifica.setVisible(true);
        }
        else{
            jMenuJucator.setVisible(false);
            jMenuJucatorModifica.setVisible(false);
        }
    }
    
    private void privilegii_antrenor(String adauga_antrenor, String modifica_antrenor){
        if(adauga_antrenor.contentEquals("0")){
            jMenuAntrenor.setVisible(true);
            jMenuAntrenorAdauga.setVisible(true);
        }
        else{
            jMenuAntrenor.setVisible(false);
            jMenuAntrenorAdauga.setVisible(false);
        }
        
        if(modifica_antrenor.contentEquals("0")){
            jMenuAntrenor.setVisible(true);
            jMenuAntrenorModifica.setVisible(true);
        }
        else{
            jMenuAntrenor.setVisible(false);
            jMenuAntrenorModifica.setVisible(false);
        }
    }
    
    private void privilegii_grupa(String adauga_grupa, String modifica_grupa){
        if(adauga_grupa.contentEquals("0")){
            jMenuGrupa.setVisible(true);
            jMenuGrupaAdauga.setVisible(true);
        }
        else{
            jMenuGrupa.setVisible(false);
            jMenuGrupaAdauga.setVisible(false);
        }
        
        if(modifica_grupa.contentEquals("0")){
            jMenuGrupa.setVisible(true);
            jMenuGrupaModifica.setVisible(true);
        }
        else{
            jMenuGrupa.setVisible(false);
            jMenuGrupaModifica.setVisible(false);
        }
    }
    
    private void privilegii_antrenamente(String adauga_antrenament, String modifica_antrenament){
        if(adauga_antrenament.contentEquals("0")){
            jMenuAntrenament.setVisible(true);
            jMenuAntrenamentAdauga.setVisible(true);
        }
        else{
            jMenuAntrenament.setVisible(false);
            jMenuAntrenamentAdauga.setVisible(false);
        }
        
        if(modifica_antrenament.contentEquals("0")){
            jMenuAntrenament.setVisible(true);
            jMenuAntrenamentModifica.setVisible(true);
        }
        else{
            jMenuAntrenament.setVisible(false);
            jMenuAntrenamentModifica.setVisible(false);
        }
    }
    
    private void privilegii_setari(String setari){
        if(setari.contentEquals("0")){
            jMenuSetari.setVisible(true);
        }
        else{
            jMenuSetari.setVisible(false);
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMeniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMeniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMeniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMeniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainMeniu().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MainMeniu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAntrenament;
    private javax.swing.JMenuItem jMenuAntrenamentAdauga;
    private javax.swing.JMenuItem jMenuAntrenamentModifica;
    private javax.swing.JMenu jMenuAntrenor;
    private javax.swing.JMenuItem jMenuAntrenorAdauga;
    private javax.swing.JMenuItem jMenuAntrenorModifica;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGrupa;
    private javax.swing.JMenuItem jMenuGrupaAdauga;
    private javax.swing.JMenuItem jMenuGrupaModifica;
    private javax.swing.JMenu jMenuJucator;
    private javax.swing.JMenuItem jMenuJucatorAdauga;
    private javax.swing.JMenuItem jMenuJucatorModifica;
    private javax.swing.JMenu jMenuSetari;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    // End of variables declaration//GEN-END:variables
}