/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainSiLogin;

import Antrenament.AdaugaAntrenament;
import Grupe.AdaugaGrupa;
import Jucator.AdaugaJucator;
import Utilizatori.AdaugaUsers;
import Jucator.ModificaJucator;
import Utilizatori.ModificaUtilizatori;
import clase.DBConnection;
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.net.URL;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author TechSolutions
 */
public class MainMeniu extends javax.swing.JFrame {

    Connection connect = DBConnection.getDbCon().connect;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    public MainMeniu() throws SQLException {
        initComponents();
        String adauga_jucator = Login.rs.getString("adauga_jucator");
        String modifica_jucator = Login.rs.getString("modifica_jucator");
        privilegii_jucator(adauga_jucator, modifica_jucator);
        
        String adauga_antrenor = Login.rs.getString("adauga_antrenor");
        String modifica_antrenor = Login.rs.getString("modifica_antrenor");
        privilegii_antrenor(adauga_antrenor, modifica_antrenor);
        
        String adauga_grupa = Login.rs.getString("adauga_grupa");
        String modifica_grupa = Login.rs.getString("modifica_grupa");
        privilegii_grupa(adauga_grupa, modifica_grupa);
        
        String adauga_antrenament = Login.rs.getString("adauga_antrenament");
        String modifica_antrenament = Login.rs.getString("modifica_antrenament");
        privilegii_antrenamente(adauga_antrenament, modifica_antrenament);
        
        String setari = Login.rs.getString("setari");
        privilegii_setari(setari);
        
        CompletareDate();
        
        PopuleazaTabela();
        AfisarePoza();
    }
    
    private void AfisarePoza() throws SQLException{
        String name = Login.rs.getString("prenume") ;
        ImageIcon icon =new ImageIcon("lib\\poze\\" + name + ".jpg");
            jPoza.setPreferredSize(new Dimension(144,121));
            jPoza.setIcon(icon);
        
    }
    
    
    private void PopuleazaTabela() throws SQLException{
        int id_grupa = Login.rs.getInt("grupa");
        String sql = "Select `j`.`id`, `j`.`nume`, j.prenume, `p`.`denumire` from `jucator` `j` left join `posturi` `p` ON `p`.`id_post` = `j`.`id_post` where `j`.`id_grupa`='" + id_grupa + "'";
        PreparedStatement ps = connect.prepareStatement(sql);
        rs = ps.executeQuery();
            jTabelaEchipa_MainMeniu.setModel(DbUtils.resultSetToTableModel(rs));
    }
    private void PreluareEchipa(){
        try{
            int id_grupa = Login.rs.getInt("grupa");
            String sql="Select denumire from grupe where id_grupa = '"+id_grupa+"'";
            ps=connect.prepareStatement(sql);
            rs=ps.executeQuery();
            while(rs.next())
            {
                String denumire =rs.getString("denumire");
                jtfEchipa_MainMeniu.setText(denumire);
            }
        }
       
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    private void CompletareDate() throws SQLException{
        String nume = Login.rs.getString("nume");
        jtfNume_MAINMENIU.setText(nume);
        
        String prenume = Login.rs.getString("prenume");
        jtfPrenume_MAINMENIU.setText(prenume);

        PreluareEchipa();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jtfNume_MAINMENIU = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfPrenume_MAINMENIU = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfEchipa_MainMeniu = new javax.swing.JTextField();
        jPoza = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaEchipa_MainMeniu = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuJucator = new javax.swing.JMenu();
        jMenuJucatorAdauga = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuJucatorModifica = new javax.swing.JMenuItem();
        jMenuAntrenor = new javax.swing.JMenu();
        jMenuAntrenorAdauga = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuAntrenorModifica = new javax.swing.JMenuItem();
        jMenuGrupa = new javax.swing.JMenu();
        jMenuGrupaAdauga = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuGrupaModifica = new javax.swing.JMenuItem();
        jMenuAntrenament = new javax.swing.JMenu();
        jMenuAntrenamentAdauga = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuAntrenamentModifica = new javax.swing.JMenuItem();
        jMenuSetari = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicatie Management - MainMeniu");
        setMinimumSize(new java.awt.Dimension(700, 500));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setText("Nume:");

        jtfNume_MAINMENIU.setEditable(false);

        jLabel2.setText("Prenume:");

        jtfPrenume_MAINMENIU.setEditable(false);

        jLabel3.setText("Echipa:");

        jtfEchipa_MainMeniu.setEditable(false);

        jPoza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resurse/Login-2.jpg"))); // NOI18N
        jPoza.setMaximumSize(new java.awt.Dimension(144, 121));
        jPoza.setMinimumSize(new java.awt.Dimension(144, 121));
        jPoza.setPreferredSize(new java.awt.Dimension(144, 121));

        jTabelaEchipa_MainMeniu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTabelaEchipa_MainMeniu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nume", "Prenume", "Post", "APT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelaEchipa_MainMeniu.setEnabled(false);
        jTabelaEchipa_MainMeniu.setFillsViewportHeight(true);
        jTabelaEchipa_MainMeniu.setFocusable(false);
        jTabelaEchipa_MainMeniu.setGridColor(new java.awt.Color(153, 153, 153));
        jTabelaEchipa_MainMeniu.setOpaque(false);
        jTabelaEchipa_MainMeniu.setRequestFocusEnabled(false);
        jTabelaEchipa_MainMeniu.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTabelaEchipa_MainMeniu.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTabelaEchipa_MainMeniu);

        jMenuJucator.setText("Jucator");

        jMenuJucatorAdauga.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuJucatorAdauga.setText("Adauga Jucator");
        jMenuJucatorAdauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuJucatorAdaugaActionPerformed(evt);
            }
        });
        jMenuJucator.add(jMenuJucatorAdauga);
        jMenuJucator.add(jSeparator1);

        jMenuJucatorModifica.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuJucatorModifica.setText("Modifica Jucator");
        jMenuJucatorModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuJucatorModificaActionPerformed(evt);
            }
        });
        jMenuJucator.add(jMenuJucatorModifica);

        jMenuBar1.add(jMenuJucator);

        jMenuAntrenor.setText("Antrenor");

        jMenuAntrenorAdauga.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuAntrenorAdauga.setText("Adauga ");
        jMenuAntrenorAdauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAntrenorAdaugaActionPerformed(evt);
            }
        });
        jMenuAntrenor.add(jMenuAntrenorAdauga);
        jMenuAntrenor.add(jSeparator2);

        jMenuAntrenorModifica.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuAntrenorModifica.setText("Modifica");
        jMenuAntrenorModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAntrenorModificaActionPerformed(evt);
            }
        });
        jMenuAntrenor.add(jMenuAntrenorModifica);

        jMenuBar1.add(jMenuAntrenor);

        jMenuGrupa.setText("Grupa");

        jMenuGrupaAdauga.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, 0));
        jMenuGrupaAdauga.setText("Adauga");
        jMenuGrupaAdauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGrupaAdaugaActionPerformed(evt);
            }
        });
        jMenuGrupa.add(jMenuGrupaAdauga);
        jMenuGrupa.add(jSeparator3);

        jMenuGrupaModifica.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, 0));
        jMenuGrupaModifica.setText("Modifica");
        jMenuGrupa.add(jMenuGrupaModifica);

        jMenuBar1.add(jMenuGrupa);

        jMenuAntrenament.setText("Antrenament");

        jMenuAntrenamentAdauga.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuAntrenamentAdauga.setText("Adauga");
        jMenuAntrenamentAdauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAntrenamentAdaugaActionPerformed(evt);
            }
        });
        jMenuAntrenament.add(jMenuAntrenamentAdauga);
        jMenuAntrenament.add(jSeparator4);

        jMenuAntrenamentModifica.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuAntrenamentModifica.setText("Modifica");
        jMenuAntrenamentModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAntrenamentModificaActionPerformed(evt);
            }
        });
        jMenuAntrenament.add(jMenuAntrenamentModifica);

        jMenuBar1.add(jMenuAntrenament);

        jMenuSetari.setText("Setari");
        jMenuBar1.add(jMenuSetari);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfNume_MAINMENIU)
                            .addComponent(jtfPrenume_MAINMENIU)
                            .addComponent(jtfEchipa_MainMeniu, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPoza, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPoza, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfNume_MAINMENIU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfPrenume_MAINMENIU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfEchipa_MainMeniu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator5)
        );

        getAccessibleContext().setAccessibleName("E-Management - MainMeniu");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuJucatorAdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuJucatorAdaugaActionPerformed
        // TODO add your handling code here:
        AdaugaJucator aj = new AdaugaJucator();
        aj.setVisible(true);
    }//GEN-LAST:event_jMenuJucatorAdaugaActionPerformed

    private void jMenuJucatorModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuJucatorModificaActionPerformed
        // TODO add your handling code here:
        ModificaJucator mj = new ModificaJucator();
        mj.setVisible(true);
    }//GEN-LAST:event_jMenuJucatorModificaActionPerformed

    private void jMenuAntrenorModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAntrenorModificaActionPerformed
        // TODO add your handling code here:
        ModificaUtilizatori mu;
        try {
            mu = new ModificaUtilizatori();
            mu.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MainMeniu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuAntrenorModificaActionPerformed

    private void jMenuAntrenamentModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAntrenamentModificaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAntrenamentModificaActionPerformed

    private void jMenuAntrenorAdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAntrenorAdaugaActionPerformed
        // TODO add your handling code here:
        AdaugaUsers au = new AdaugaUsers();
        au.setVisible(true);
    }//GEN-LAST:event_jMenuAntrenorAdaugaActionPerformed

    private void jMenuGrupaAdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGrupaAdaugaActionPerformed
        // TODO add your handling code here:
        AdaugaGrupa ag = new AdaugaGrupa();
        ag.setVisible(true);
    }//GEN-LAST:event_jMenuGrupaAdaugaActionPerformed

    private void jMenuAntrenamentAdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAntrenamentAdaugaActionPerformed
        // TODO add your handling code here:
        AdaugaAntrenament aa = new AdaugaAntrenament();
        aa.setVisible(true);
    }//GEN-LAST:event_jMenuAntrenamentAdaugaActionPerformed

    private void privilegii_jucator(String adauga_jucator, String modifica_jucator){
        if(adauga_jucator.contentEquals("0")){
            jMenuJucator.setVisible(true);
            jMenuJucatorAdauga.setVisible(true);
        }
        else{
            jMenuJucator.setVisible(false);
            jMenuJucatorAdauga.setVisible(false);
        }
        
        if(modifica_jucator.contentEquals("0")){
            jMenuJucator.setVisible(true);
            jMenuJucatorModifica.setVisible(true);
        }
        else{
            jMenuJucator.setVisible(false);
            jMenuJucatorModifica.setVisible(false);
        }
    }
    
    private void privilegii_antrenor(String adauga_antrenor, String modifica_antrenor){
        if(adauga_antrenor.contentEquals("0")){
            jMenuAntrenor.setVisible(true);
            jMenuAntrenorAdauga.setVisible(true);
        }
        else{
            jMenuAntrenor.setVisible(false);
            jMenuAntrenorAdauga.setVisible(false);
        }
        
        if(modifica_antrenor.contentEquals("0")){
            jMenuAntrenor.setVisible(true);
            jMenuAntrenorModifica.setVisible(true);
        }
        else{
            jMenuAntrenor.setVisible(false);
            jMenuAntrenorModifica.setVisible(false);
        }
    }
    
    private void privilegii_grupa(String adauga_grupa, String modifica_grupa){
        if(adauga_grupa.contentEquals("0")){
            jMenuGrupa.setVisible(true);
            jMenuGrupaAdauga.setVisible(true);
        }
        else{
            jMenuGrupa.setVisible(false);
            jMenuGrupaAdauga.setVisible(false);
        }
        
        if(modifica_grupa.contentEquals("0")){
            jMenuGrupa.setVisible(true);
            jMenuGrupaModifica.setVisible(true);
        }
        else{
            jMenuGrupa.setVisible(false);
            jMenuGrupaModifica.setVisible(false);
        }
    }
    
    private void privilegii_antrenamente(String adauga_antrenament, String modifica_antrenament){
        if(adauga_antrenament.contentEquals("0")){
            jMenuAntrenament.setVisible(true);
            jMenuAntrenamentAdauga.setVisible(true);
        }
        else{
            jMenuAntrenament.setVisible(false);
            jMenuAntrenamentAdauga.setVisible(false);
        }
        
        if(modifica_antrenament.contentEquals("0")){
            jMenuAntrenament.setVisible(true);
            jMenuAntrenamentModifica.setVisible(true);
        }
        else{
            jMenuAntrenament.setVisible(false);
            jMenuAntrenamentModifica.setVisible(false);
        }
    }
    
    private void privilegii_setari(String setari){
        if(setari.contentEquals("0")){
            jMenuSetari.setVisible(true);
        }
        else{
            jMenuSetari.setVisible(false);
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMeniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMeniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMeniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMeniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainMeniu().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MainMeniu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenuAntrenament;
    private javax.swing.JMenuItem jMenuAntrenamentAdauga;
    private javax.swing.JMenuItem jMenuAntrenamentModifica;
    private javax.swing.JMenu jMenuAntrenor;
    private javax.swing.JMenuItem jMenuAntrenorAdauga;
    private javax.swing.JMenuItem jMenuAntrenorModifica;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGrupa;
    private javax.swing.JMenuItem jMenuGrupaAdauga;
    private javax.swing.JMenuItem jMenuGrupaModifica;
    private javax.swing.JMenu jMenuJucator;
    private javax.swing.JMenuItem jMenuJucatorAdauga;
    private javax.swing.JMenuItem jMenuJucatorModifica;
    private javax.swing.JMenu jMenuSetari;
    private javax.swing.JLabel jPoza;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTabelaEchipa_MainMeniu;
    private javax.swing.JTextField jtfEchipa_MainMeniu;
    private javax.swing.JTextField jtfNume_MAINMENIU;
    private javax.swing.JTextField jtfPrenume_MAINMENIU;
    // End of variables declaration//GEN-END:variables

    
}