/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utilizatori;

import clase.DBConnection;
import clase.Users;
import clase.criptare;
import com.mysql.jdbc.Connection;
import java.beans.Visibility;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author TechSolutions
 */
public class AdaugaUsers extends javax.swing.JFrame{

    /**
     * Creates new form AdaugaUsers
     */
    Connection connect = DBConnection.getDbCon().connect;
    PreparedStatement ps = null;
    ResultSet rs = null;
    Users utilizator = new Users();
    
    
    
    public AdaugaUsers() {
        initComponents();
        InserareFunctie();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtf_utilizator = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtf_nume = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtf_prenume = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtf_telefon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_adresa = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jtf_cnp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jcb_functie = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jbtn_adauga_user = new javax.swing.JButton();
        jbtn_cancel_users = new javax.swing.JButton();
        jpf_parola = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jcb_functie1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aplicatie Management - Adauga Utilizator");
        setMinimumSize(new java.awt.Dimension(569, 330));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adauga User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), java.awt.Color.black)); // NOI18N

        jLabel1.setText("Utilizator:");

        jLabel2.setText("Parola:");

        jLabel3.setText("Nume:");

        jLabel4.setText("Prenume:");

        jLabel5.setText("Telefon:");

        jLabel6.setText("Adresa:");

        jta_adresa.setColumns(20);
        jta_adresa.setRows(5);
        jScrollPane1.setViewportView(jta_adresa);

        jLabel7.setText("CNP:");

        jLabel8.setText("Functie:");

        jcb_functie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alege Functie" }));
        jcb_functie.setToolTipText("");

        jbtn_adauga_user.setText("Adauga");
        jbtn_adauga_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_adauga_userActionPerformed(evt);
            }
        });

        jbtn_cancel_users.setText("Cancel");
        jbtn_cancel_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cancel_usersActionPerformed(evt);
            }
        });

        jLabel9.setText("Grupa");

        jcb_functie1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alege grupa" }));
        jcb_functie1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(622, 622, 622)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel2))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(13, 13, 13)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(32, 32, 32)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtf_telefon)
                                    .addComponent(jtf_utilizator, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_cnp)
                                    .addComponent(jpf_parola, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addGap(160, 160, 160)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn_adauga_user, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jtf_nume)
                                                .addComponent(jtf_prenume, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(8, 8, 8)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel8))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jcb_functie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel9)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jcb_functie1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addComponent(jbtn_cancel_users))
                        .addGap(101, 101, 101)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtf_utilizator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtf_nume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jtf_prenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpf_parola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtf_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel6)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtf_cnp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jcb_functie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jcb_functie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_cancel_users)
                    .addComponent(jbtn_adauga_user))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("E-Management - Adauga Utilizator");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_cancel_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cancel_usersActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jbtn_cancel_usersActionPerformed

    private void jbtn_adauga_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_adauga_userActionPerformed
        // TODO add your handling code here:
        
        //verificare campuri completate
        if(jtf_utilizator.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Va rugam sa completati un nume de utilizator !");
        }
        else
           if(jtf_nume.getText().isEmpty()){
               JOptionPane.showMessageDialog(null, "Va rugam sa completati numele dumneavoastra !");
           }
        else
            if(jpf_parola.getText().isEmpty()){
               JOptionPane.showMessageDialog(null, "Va rugam sa completati parola asociata contului, cu care trebuie sa va logati in aplicatie !");
            }
        else
            if(jtf_prenume.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Va rugam sa completati prenumele dumneavoastra !");
            }
        else
                if(jtf_telefon.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Va rugam sa completati telefonul dumneavoastra !");
                }
        else
                    if(jta_adresa.getText().isEmpty()){
                        JOptionPane.showMessageDialog(null, "Va rugam sa completati adresa dumneavoastra !");
                    }
        else
                    if(jcb_functie.getSelectedIndex()==0){
                        JOptionPane.showMessageDialog(null, "Va rugam sa alegeti o functie pentru utilizatorul dumneavoastra !");
                    }
        else
                        if(jtf_cnp.getText().isEmpty()){
                            JOptionPane.showMessageDialog(null, "Va rugam sa introduce-ti cnp-ul dumneavoastra!");
                        }
        else
                        //verificare lungime cnp corespunzatoare
        if((jtf_cnp.getText().length() < 13) || (jtf_cnp.getText().length() > 13)){
            JOptionPane.showMessageDialog(null, "CNP-ul corect nu este valid, doarece nu respecta lungimea");
        }
        else
                        {
                            utilizator.setUser(jtf_utilizator.getText());
                            utilizator.setNume(jtf_nume.getText());
            try {
                utilizator.setParola(criptare.MD5(jpf_parola.getText()));
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(AdaugaUsers.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(AdaugaUsers.class.getName()).log(Level.SEVERE, null, ex);
            }
                            utilizator.setPrenume(jtf_prenume.getText());
                            utilizator.setTelefon(jtf_telefon.getText());
                            utilizator.setAdresa(jta_adresa.getText());
                            utilizator.setFunctie(jcb_functie.getSelectedIndex());
                            utilizator.setCnp(jtf_cnp.getText());
                            System.out.println(utilizator.Afisare_User());
                            
                            //apelam functia de inserare bd
                            InserareUsersBD();
                            setVisible(false);
                        }
    }//GEN-LAST:event_jbtn_adauga_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdaugaUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdaugaUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdaugaUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdaugaUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdaugaUsers().setVisible(true);
            }
        });
    }
    
    private void InserareUsersBD(){
        String sql = "Insert into utilizatori(utilizator, parola, nume, prenume, telefon, adresa, functie, cnp) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            try {
                PreparedStatement ps = connect.prepareStatement(sql);
                ps.setString(1, utilizator.getUser());
                ps.setString(2, utilizator.getParola());
                ps.setString(3, utilizator.getNume());
                ps.setString(4, utilizator.getPrenume());
                ps.setString(5, utilizator.getTelefon());
                ps.setString(6, utilizator.getAdresa());
                ps.setInt(7, utilizator.getFunctie());
                ps.setString(8, utilizator.getCnp());
                ps.executeUpdate();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            } 
            try{
            rs.close();
            ps.close();
            System.out.println("Inchidere rs si ps!");
        }
        //exceptie inchidere bd
        catch(Exception eibd){
            JOptionPane.showMessageDialog(null, eibd);
        }
    }
    
    private void InserareFunctie(){
        try{
            String sql = "Select * from functie where denumire = 'Antrenor'";
            ps=connect.prepareStatement(sql);
            rs=ps.executeQuery();
            while(rs.next()){
                int id = rs.getInt("id");
                String denumire =rs.getString("denumire");
                jcb_functie.insertItemAt(denumire, id);
                
            }
        }
        catch(Exception exip){
            JOptionPane.showMessageDialog(null, exip);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_adauga_user;
    private javax.swing.JButton jbtn_cancel_users;
    private javax.swing.JComboBox jcb_functie;
    private javax.swing.JComboBox jcb_functie1;
    private javax.swing.JPasswordField jpf_parola;
    private javax.swing.JTextArea jta_adresa;
    private javax.swing.JTextField jtf_cnp;
    private javax.swing.JTextField jtf_nume;
    private javax.swing.JTextField jtf_prenume;
    private javax.swing.JTextField jtf_telefon;
    private javax.swing.JTextField jtf_utilizator;
    // End of variables declaration//GEN-END:variables
}
