/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewInterface;

import Administrativ.Administrativ;
import Tehnic.Tehnic;
import javax.swing.JLabel;

/**
 *
 * @author GSoftware
 */
public class MainMeniu2 extends javax.swing.JFrame {

    /**
     * Creates new form MainMeniu
     */
    public MainMeniu2() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAdministrativ = new javax.swing.JMenu();
        jMenuTehnic = new javax.swing.JMenu();
        jMenuInstructiv_Educativ = new javax.swing.JMenu();
        jMenuSelectii = new javax.swing.JMenu();
        jMenuCompetitii = new javax.swing.JMenu();
        jCompetitii_FCVII = new javax.swing.JMenuItem();
        jCompetitii_Juniori_A = new javax.swing.JMenuItem();
        jCompetitii_Juniori_B = new javax.swing.JMenuItem();
        jCompetitii_Juniori_C = new javax.swing.JMenuItem();
        jCompetitii_Juniori_C1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenu18 = new javax.swing.JMenu();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Interface");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );

        jMenuAdministrativ.setText("Administrativ");
        jMenuAdministrativ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAdministrativMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuAdministrativ);

        jMenuTehnic.setText("Tehnic");
        jMenuTehnic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuTehnicMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuTehnic);

        jMenuInstructiv_Educativ.setText("Instructiv - Educativ");
        jMenuBar1.add(jMenuInstructiv_Educativ);

        jMenuSelectii.setText("Selectii");
        jMenuBar1.add(jMenuSelectii);

        jMenuCompetitii.setText("Competitii");

        jCompetitii_FCVII.setText("FCV II");
        jMenuCompetitii.add(jCompetitii_FCVII);

        jCompetitii_Juniori_A.setText("Juniori A");
        jMenuCompetitii.add(jCompetitii_Juniori_A);

        jCompetitii_Juniori_B.setText("Juniori B");
        jMenuCompetitii.add(jCompetitii_Juniori_B);

        jCompetitii_Juniori_C.setText("Juniori C");
        jMenuCompetitii.add(jCompetitii_Juniori_C);

        jCompetitii_Juniori_C1.setText("Juniori C1");
        jMenuCompetitii.add(jCompetitii_Juniori_C1);

        jMenuBar1.add(jMenuCompetitii);

        jMenu6.setText("Orar Zilnic");

        jMenuItem6.setText("Orar Liber in Oras");
        jMenu6.add(jMenuItem6);

        jMenuItem7.setText("Orar Scolar");
        jMenu6.add(jMenuItem7);

        jMenuItem8.setText("Orar Hotel");
        jMenu6.add(jMenuItem8);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Program Antrenament");

        jMenuItem9.setText("Repartizare Terenuri");
        jMenu7.add(jMenuItem9);

        jMenuItem10.setText("Autocar");
        jMenu7.add(jMenuItem10);

        jMenu10.setText("Individualizari Fizice");

        jMenuItem11.setText("Sala Forta");
        jMenu10.add(jMenuItem11);

        jMenuItem12.setText("Teren");
        jMenu10.add(jMenuItem12);

        jMenu7.add(jMenu10);

        jMenu11.setText("Individualizari Tehnice");

        jMenuItem13.setText("FCV II");
        jMenu11.add(jMenuItem13);

        jMenuItem14.setText("Juniori A");
        jMenu11.add(jMenuItem14);

        jMenuItem15.setText("Juniori B");
        jMenu11.add(jMenuItem15);

        jMenuItem16.setText("Juniori C");
        jMenu11.add(jMenuItem16);

        jMenuItem17.setText("Juniori C1");
        jMenu11.add(jMenuItem17);

        jMenuItem18.setText("Juniori D");
        jMenu11.add(jMenuItem18);

        jMenu7.add(jMenu11);

        jMenu12.setText("Programare Discutii Individuale Jucatori");

        jMenuItem19.setText("FCV II");
        jMenu12.add(jMenuItem19);

        jMenuItem20.setText("Juniori A");
        jMenu12.add(jMenuItem20);

        jMenuItem21.setText("Juniori B");
        jMenu12.add(jMenuItem21);

        jMenuItem22.setText("Juniori C");
        jMenu12.add(jMenuItem22);

        jMenuItem23.setText("Juniori D");
        jMenu12.add(jMenuItem23);

        jMenu7.add(jMenu12);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Loturi");

        jMenuItem24.setText("FCV II");
        jMenu8.add(jMenuItem24);

        jMenuItem25.setText("Juniori A");
        jMenu8.add(jMenuItem25);

        jMenuItem26.setText("Juniori B");
        jMenu8.add(jMenuItem26);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Jucatori");

        jMenu13.setText("Evaluare Individuala Disciplinar - Scolar");

        jMenuItem27.setText("Disciplinar");
        jMenu13.add(jMenuItem27);

        jMenu14.setText("Scolar");

        jMenuItem28.setText("Note si Medii Scolare");
        jMenu14.add(jMenuItem28);

        jMenuItem29.setText("Absente");
        jMenu14.add(jMenuItem29);

        jMenu13.add(jMenu14);

        jMenu9.add(jMenu13);

        jMenu15.setText("Evaluare Individuala Plan Sportiv");

        jMenu16.setText("TE / TA / Fi / ME");

        jMenu19.setText("Tehnic");

        jMenuItem31.setText("Teste Tehnice Intermediare");
        jMenu19.add(jMenuItem31);

        jMenuItem36.setText("Teste Tehnice Anuale");
        jMenu19.add(jMenuItem36);

        jMenuItem37.setText("Analiza Meci ( Tehnic Individual )");
        jMenu19.add(jMenuItem37);

        jMenu16.add(jMenu19);

        jMenu18.setText("Tactic");

        jMenuItem32.setText("Analiza Meci ( Tactic Individual )");
        jMenu18.add(jMenuItem32);

        jMenu16.add(jMenu18);

        jMenu17.setText("Fizica");

        jMenuItem33.setText("Teste Fizice Intermediare");
        jMenu17.add(jMenuItem33);

        jMenuItem35.setText("Teste Fizice Anuale");
        jMenu17.add(jMenuItem35);

        jMenu16.add(jMenu17);

        jMenuItem34.setText("Mental");
        jMenu16.add(jMenuItem34);

        jMenu15.add(jMenu16);

        jMenuItem30.setText("Analiza Antrenament");
        jMenu15.add(jMenuItem30);

        jMenu9.add(jMenu15);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAdministrativMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAdministrativMouseClicked
        // TODO add your handling code here:
        Administrativ adm = new Administrativ();
        adm.setVisible(true);
    }//GEN-LAST:event_jMenuAdministrativMouseClicked

    //Functie de citire si acordare drepturi de folosinta a interfetei.
    private void Drepturi(){
        int administrativ = 0;
        int tehnic = 0;
        int instructiv_educativ = 0;
        int selectii = 0;
        int competitii = 0;
        
        if(administrativ == 0){
            jMenuAdministrativ.setVisible(false);
        }
        else if(administrativ == 1){
            jMenuAdministrativ.setVisible(true);
        }
        else if(tehnic == 0){
            jMenuTehnic.setVisible(false);
        }
        else if(tehnic == 1){
            jMenuTehnic.setVisible(true);
        }
        else if(instructiv_educativ == 0){
            jMenuInstructiv_Educativ.setVisible(false);
        }
        else if(instructiv_educativ == 1){
            jMenuInstructiv_Educativ.setVisible(true);
        }
        else if (selectii == 0){
            jMenuSelectii.setVisible(false);
        }
        else if (selectii == 1){
            jMenuSelectii.setVisible(true);
        }
        else if (competitii == 0){
            jMenuCompetitii.setVisible(false);
        }
        else if (competitii == 1){
            jMenuCompetitii.setVisible(true);
        }
        else if (competitii == 2){
            jMenuCompetitii.setVisible(true);
            jCompetitii_FCVII.setVisible(true);
        }
        else if (competitii == 3){
            jMenuCompetitii.setVisible(true);
            jCompetitii_FCVII.setVisible(true);
            jCompetitii_Juniori_A.setVisible(true);
        }
        else if (competitii == 4){
            jMenuCompetitii.setVisible(true);
            jCompetitii_FCVII.setVisible(true);
            jCompetitii_Juniori_A.setVisible(true);
            jCompetitii_Juniori_B.setVisible(true);
        }
        else if (competitii == 5){
            jMenuCompetitii.setVisible(true);
            jCompetitii_FCVII.setVisible(true);
            jCompetitii_Juniori_A.setVisible(true);
            jCompetitii_Juniori_B.setVisible(true);
            jCompetitii_Juniori_C.setVisible(true);
        }
        else if (competitii == 6){
            jMenuCompetitii.setVisible(true);
            jCompetitii_FCVII.setVisible(true);
            jCompetitii_Juniori_A.setVisible(true);
            jCompetitii_Juniori_B.setVisible(true);
            jCompetitii_Juniori_C.setVisible(true);
            jCompetitii_Juniori_C1.setVisible(true);
        }
    }
    
    
    private void jMenuTehnicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuTehnicMouseClicked
        // TODO add your handling code here:
        Tehnic th = new Tehnic();
        th.setVisible(true);
    }//GEN-LAST:event_jMenuTehnicMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMeniu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMeniu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMeniu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMeniu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMeniu2().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jCompetitii_FCVII;
    private javax.swing.JMenuItem jCompetitii_Juniori_A;
    private javax.swing.JMenuItem jCompetitii_Juniori_B;
    private javax.swing.JMenuItem jCompetitii_Juniori_C;
    private javax.swing.JMenuItem jCompetitii_Juniori_C1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenu jMenuAdministrativ;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCompetitii;
    private javax.swing.JMenu jMenuInstructiv_Educativ;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu jMenuSelectii;
    private javax.swing.JMenu jMenuTehnic;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
